version: "3.8"
services:
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://week08_utxh_user:AOipiBuHv1UvBH98BtIwqwdC1eLppyFs@dpg-crl9ctjtq21c73eakq8g-a.oregon-postgres.render.com/week08_utxh

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://week08_utxh_user:AOipiBuHv1UvBH98BtIwqwdC1eLppyFs@dpg-crl9ctjtq21c73eakq8g-a.oregon-postgres.render.com/week08_utxh
