FROM python:3.11-alpine
WORKDIR /app/
COPY inventory_management/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY inventory_management/ .
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${PORT:-8001}"]